### ISSUE TITLE
Integration with 2 zones (second zone is missing)

### ISSUE THREAD

**Issue by Mavo81** [cjaliaga/home-assistant-aquarea#20]
Hi,
I have heat pump with 2 zones:

1st is named as ‘podlahovka’ (= floor heating)
2nd is ‘radiator’

![img1](https://user-images.githubusercontent.com/99136758/191330970-26860255-8126-4e01-b4d4-5670b03a5ed2.png)

In home assistant I see only entity ID climate.majco_podlahovka, second zone is missing:

![integrations](https://user-images.githubusercontent.com/99136758/191329030-c1bddf68-dc20-4271-9223-82a99f2c1c56.png)

In HA log I see this error:

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:520
Integration: Klimatizácia (documentation, issues)
First occurred: 20:14:26 (2 occurrences)
Last logged: 20:20:26

Platform aquarea does not generate unique IDs. ID None_heatpump already exists - ignoring climate.majco_podlahovka
```

If you need anything to add or test I'm here to asssist.

Marian

**Comment by Yetiii1986** [comment]
I've the same problem.

**Comment by cjaliaga** [comment]
Thanks @Mavo81 and @Yetiii1986 for reporting the issue. The next version released will contain the fix for it. As we discussed on Home Assistant Forums: [Panasonic Aquarea Heat Pump integration](https://community.home-assistant.io/t/panasonic-aquarea-heat-pump-integration/392095/55?u=cjaliaga), it will be a breaking change. 

The recommendation is to remove the integration before updating, and readding it after it.

Thanks!
